"""add content column to roadmap_stages

Revision ID: 57c224d0d92b
Revises: f989abf2de21
Create Date: 2026-09-03 12:59:59.746187
"""
from alembic import op
import sqlalchemy as sa


revision = '57c224d0d92b'
down_revision = 'f989abf2de21'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roadmap_stages', sa.Column('content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roadmap_stages', 'content')
    # ### end Alembic commands ###
